name: Build Release APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create signing keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > jugaad-release-key.jks
      
    - name: Build Release APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease
      
    # Upload as artifact (for backup/debugging)
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jugaad-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    # Create public release on every push to main
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.sha }}
        name: "Build ${{ github.sha }}"
        body: |
          Automatic release from commit ${{ github.sha }}
          
          **Commit:** ${{ github.event.head_commit.message }}
          **Author:** ${{ github.event.head_commit.author.name }}
        files: app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
